apiVersion: 1

datasources:
  - name: GridSense PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: gridsense
    user: gridsense
    secureJsonData:
      password: gridsense
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true

  - name: GridSense API
    type: grafana-simple-json-datasource
    access: proxy
    url: http://backend:8000/api/grafana
    isDefault: false
    editable: true